map_type: costmap
transform_tolerance: 0.2
obstacle_range: 30.0
max_obstacle_height: 2.0
raytrace_range: 15.0
inscribed_radius: 0.35
circumscribed_radius: 0.4
inflation_radius: 0.55
cost_scaling_factor: 15.0
lethal_cost_threshold: 100
observation_sources: hokuyo_laser_scan_sensor


hokuyo_laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, 
                           marking: true, clearing: true,  expected_update_rate: 0.1}


