TrajectoryPlannerROS:
  transform_tolerance: 0.2
  world_model: costmap
  sim_time: 2.0
  sim_granularity: 0.025
  dwa: false
  vx_samples: 3
  vtheta_samples: 20
  max_vel_x: 0.8
  min_vel_x: 0.3
  max_vel_th: 1.0
  min_vel_th: -1.0
  min_in_place_vel_th: 0.4
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.1
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.1
  escape_reset_dist: 0.15
  escape_reset_theta: 0.30
  acc_lim_th: 5.0
  acc_lim_x: 3.0
  acc_lim_y: 0.0
  heading_scoring: true
  heading_scoring_timestep: 0.2
  holonomic_robot: false
  simple_attractor: false